# Generated by Django 4.2.24 on 2025-11-26 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('amazon_price', models.FloatField(blank=True, null=True)),
                ('flipkart_price', models.FloatField(blank=True, null=True)),
                ('myntra_price', models.FloatField(blank=True, null=True)),
                ('amazon_link', models.URLField(blank=True, null=True)),
                ('flipkart_link', models.URLField(blank=True, null=True)),
                ('myntra_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('recognized_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200)),
                ('product_title', models.CharField(max_length=400)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('url', models.URLField(blank=True, null=True)),
                ('uploaded_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='comparison.uploadedimage')),
            ],
        ),
    ]
