# Generated by Django 4.2.24 on 2025-12-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0004_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='ProductQuery',
        ),
    ]
