# Generated by Django 4.2.24 on 2025-12-03 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0005_product_delete_price_delete_productquery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
