# Generated by Django 4.2.24 on 2025-12-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='detected_brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='detected_product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='lowest_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='lowest_store',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='search_query',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
