# Generated by Django 4.2.24 on 2025-12-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0008_productimage_detected_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='detected_brand',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='detected_product',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='lowest_price',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='lowest_store',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='search_query',
        ),
    ]
